# See https://redoc.ly/docs/cli/configuration/ for more information.
apiDefinitions:
  main : openapi/codegen.yaml
  main1 : openapi/openapi.yaml
lint:
  extends:
    - recommended
  rules:
    no-unused-components: warning
referenceDocs:
  htmlTemplate: ./docs/index.html
  theme:
    colors:
      primary:
        main: "#32329f"
