required:
  - name
properties:
  name:
    type: string
    example: ACME Corporation
  homePage:
    type: string
    format: url
    example: 'https://www.acme-corp.com'
  phone:
    type: string
    example: 408-867-5309
type: object
